### ISSUE TITLE
fixing a typo

### ISSUE THREAD

**Issue by Abiodun001-world** [m0j33d/m0j33d#1]
# In the GitHub profile README, there's a small typo in the list of programming languages:
- **Error:** "Pyhton" is currently listed instead of "Python."
- **Solution:** Update the spelling from "Pyhton" to "Python" in the README.
-  fixed "Typescript" to "TypeScript" as the correct capitalization is "TypeScript".

**Comment by m0j33d** [comment]
Thanks @Abiodun001-world, You can create a PR for the typo fix whenever you are free

**Comment by Abiodun001-world** [comment]
OK, noted. Thanks sir.

**Comment by Abiodun001-world** [comment]
😂

Abiodun Adekunle reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>

**Comment by m0j33d** [comment]
Issue fixed

**Comment by Abiodun001-world** [comment]
🧑‍💻

Abiodun Adekunle reacted via Gmail
<https://www.google.com/gmail/about/?utm_source=gmail-in-product&utm_medium=et&utm_campaign=emojireactionemail#app>
